import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Header, Navbar } from "../components";
import QueryProvider from "./query-provider";
import I18nProvider from "./i18n-provider";
import { Suspense } from "react";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
        <QueryProvider>
          <I18nProvider>
            <Header />
            <Navbar />
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
            <Footer />
          </I18nProvider>
        </QueryProvider>
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
