import type { Metadata } from "next";
import StockChartOverview from "./@stockchartoverview/page";
import StockChartContainer from "./@stockchartcontainer/page";
// import PdfTemplate from "./@pdftemplate/page";

export const metadata: Metadata = {
  title: "Stock Visualization Chart Detail",
  description: "Generated by Thang Ngo",
};

export default function StockChartLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex flex-col bg-[#171921]">
      <div className="pb-20">
        {/* <StockChartOverview /> */}
        <StockChartContainer />
        {/* <PdfTemplate /> */}
      </div>

      <main className="flex-1">{children}</main>
    </div>
  );
}
