import type { Metadata } from "next";
import StockChartOverview from "./@stockchartoverview/page";
import StockChartContainer from "./@stockchartcontainer/page";
import PdfTemplate from "./@pdftemplate/page";

export const metadata: Metadata = {
  title: "Stock Visualization Chart Detail",
  description: "Generated by Thang Ngo",
};

export default function StockChartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen relative  flex-col bg-[#171921]">
      
      <StockChartOverview />

   
      <StockChartContainer />

      <PdfTemplate />

      {/* Nội dung trang con */}
      <main className="flex-1">{children}</main>
    </div>
  );
}
